### PR TITLE
fixes/changes for tests to pass on R2025a

### LINKED ISSUE #2469: test_aaatrig: tolerance in the first test
`form` is `'odd'`.  The code of the first test (lightly modified to echo) is:
```octave
Z = linspace(0, 2*pi, 1000);
F = exp(cos(Z));
[r, ~, ~, ~, zj] = aaatrig(F, Z, form);
norm(F - r(Z), inf)
tol
pass(1,j) = ( norm(F - r(Z), inf) < tol );
```

R2018b
  ans = 
     1.0836e-13

R2024b
  ans = 
     3.8458e-12
   
Octave 11:
  ans = 1.6476e-13

 
Note in the R2024b case is bigger than tol = 2.2204e-12.  Maybe we should just slightly increase the tolerance?

### LINKED ISSUE #2470: test_gpr: test 10 failing on R2024a, and not resolved?
```matlab
% Test vertical scale (big function, fixed hyperparameter(s)):
xx = linspace(-1,1,10)';
yy = 1e100*sin(3*xx).*exp(xx);
f = gpr(xx,yy,'sigma',1e100,'L',.1);
err = norm((f(xx) - yy)./yy,Inf);
pass(7) = err < 1e-10;

f = gpr(xx,yy,'sigma',1e100);
err = norm((f(xx) - yy)./yy,Inf);
pass(8) = err < 1e-10;

f = gpr(xx,yy,'L',.1);
err = norm((f(xx) - yy)./yy,Inf);
pass(9) = err < 1e-10;


f = gpr(xx,yy)                                     # line 60
err = norm((f(xx) - yy)./yy,Inf)
pass(10) = err < 1e-10;
```

Here we get:
```
>> test_gpr
Warning: Function not resolved using 6102 pts.
> In chebfun.constructor>constructorSplit (line 252)
In chebfun.constructor (line 61)
In chebfun (line 219)
In gpr (line 120)
In test_gpr (line 60)

....

[    0.59,    0.63]        4  1.8e+100 1.8e+100
[    0.63,    0.67]      129  1.8e+100 1.8e+100
[    0.67,     0.7]        4  1.8e+100 1.7e+100
[     0.7,    0.73]        4  1.7e+100 1.7e+100
[    0.73,    0.76]        4  1.7e+100 1.6e+100
[    0.76,    0.79]        4  1.6e+100 1.5e+100
[    0.79,    0.83]        4  1.5e+100 1.4e+100
[    0.83,    0.87]      129  1.4e+100 1.2e+100
[    0.87,    0.92]      129  1.2e+100  9.3e+99
[    0.92,    0.93]        4   9.3e+99  8.5e+99
[    0.93,    0.96]      129   8.5e+99    7e+99
[    0.96,       1]      129     7e+99  3.8e+99
vertical scale = 1.8e+100    Total length = 6102

err =
   0.00010264
```

On the CI runs (different hardware, same Matlab), I get similar but
```
err =
   0.00010581
```

Tested against HEAD~1 (fe9fb5118a070c35401aac2f6745d4d3f1000c12) , and 8a42b2c246bd284c6ec523c1d37c2df575115d45

### LINKED ISSUE #2476: Fix remaining R2025a test failures and enable CI on R2025a
I have commented out the R2025a CI job temporarily in d3e4e83f8e502434f61cbb74c9409abf4387da16 (so that hopefully tests pass on the main branch).

I believe the remaining efforts are:
```
   chebfun/test_plot_xylim.m
   chebfun2/test_CLA.m
   chebop2/test_domain.m
   chebop2/test_eulerTricomi.m
   chebop2/test_generalVariableCoefficients.m
   chebop2/test_waveequation.m
   misc/test_gpr.m
   spherefun/test_optimization.m
```

I thought I fixed spherefun/test_optimization: I'll look into that one.

### PR DESCRIPTION
**Pull request by cbm755**
@nickhale here's a branch for changes need to get tests passing on R2025a.  Feel free to push directly to this  `2025a_fixes` branch., or if you prefer, send PR against this.

### TODO

  - [x] Fixes #2476 
  - [x] Fixes #2469
  - [x] Fixes #2470

### CODE REVIEW

**Comment by nickhale** [comment]
These are the two remaining failing tests
```
   chebfun/test_plot_xylim.m FAILED {2,3,6}
   misc/test_gpr.m FAILED {10}
```

Those in `test_plot_xylim` relate to the 'axis buffering' around plots. It's very heard to see why this is behaving differently on the CI run. It might relate to the screen resultion that MATLAB is running in? Since it's a cosmetic issue, I suggest we just deactivate these tests.

I have traced the failure in test_gpr.m to how lenScale is computed in parseInputs, but I can't pin it down. I suggest we just deactivate this test too.

File: gpr.m [hunk 1]
```diff
@@ -306,6 +306,7 @@
             fdom2 = fdomnew;
         end
     end
+    format long
```
Comment (cbm755) [inline gpr.m:309]:
```suggestion
```

An accidental change?

File: tests/spherefun/test_optimization.m [hunk 2]
```diff
@@ -65,6 +65,7 @@
 
 f = spherefun(@(x,y,z) exp(x));
 [m,loc] = min2(f);
-pass(j+2) = abs(loc(1) - 0) < tol;
+pass(j+2) = abs(mod(loc(1),pi) - 0) < tol;
+pass(j+3) = abs(m-0.367879441171442) < 1e-6;
```
Comment (cbm755) [inline tests/spherefun/test_optimization.m:69]:
```suggestion
pass(j+3) = abs(m-exp(-1)) < 1e-6;
```
?

My understanding here is that the min occurs at x=-1, i.e., when exp(x) = exp(-1).    so the test seems more meaningful to include that in symbols rather than a hardcoded value.

**Review by nickhale — APPROVED** [review]
